version: "3.0"
services:
  message-composer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "message-composer"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      MESSAGE_CONTENT: "Sample message"
      MESSAGE_LABEL: "alertMessage"
    ports:
      - 80:80
